- cmd/deletedeviceservice.go
- cmd/devices.go
- cmd/deviceservices.go
- cmd/profiles.go
- main.go
Updated import statement that imported `models` from edgex-go. `models` is now imported from `go-mod-core-contracts`. Adds two commands to list and delete device services
> Fixes import statement and adds two commands

- cmd/device/list/list.go
- cmd/deviceservice/list/list.go
- cmd/profile/list/list.go
Properly formatted tabled output for the following commands:
- `device list`
- `profile list`
- `deviceservice list`
> Adds table formatting to list commands

- cmd/device/add/add.go
- cmd/device/device.go
- go.mod
Allows adding new devices from definitions contained in TOML
files, similar to current device service functionality.
Implements #15 
(Note that an additional "Service" entry is required in the files to identify which device service is to manage the device)
Signed-off-by: Iain Anderson <iain@iotechsys.com>
> Add device add command

- cmd/device/list/list.go
- cmd/purgedb/purgedb.go
- cmd/root.go
- pkg/client.go
The end goal for this command is to act like a clean_mongo.js script for any underlying database. Currently, it only cleans up `core-metadata`.
TODO: clean other tables:
- coredata
- logging
- notifications
- exportclient
> Adds purgeDB which cleans up meta-data objects

- .gitignore
- cmd/device/list/list.go
- cmd/deviceservice/list/list.go
- cmd/event/list/list.go
- cmd/interval/list/list.go
- cmd/profile/list/list.go
- cmd/reading/list/list.go
- cmd/root.go
- pkg/pager/pager.go
Implements paging (a la 'less' or 'more') for the output of the list
commands.  The implementation is based on the implementation of
paging in the git cli.  The flag --no-pager is added to prevent
any paging, and the pager command defaults to less -FRX, unless
specified by the $PAGER env variable (both match the git implementation).
Signed-off-by: Daniel Harms <jdharms@gmail.com>
> implement git-style paging for list output

- cmd/db/purge/purge.go
- cmd/device/list/list.go
- cmd/device/rm/rm.go
- cmd/deviceservice/list/list.go
- cmd/deviceservice/rm/rm.go
- cmd/profile/list/list.go
- cmd/profile/rm/rm.go
- cmd/root.go
- pkg/client.go
Adds verbose flag that prints the http response's
header and body. Also removes flag logic from individual commands.
The flags are read and assigned to viper in PersistentPreRun and
read in client.
> Adds verbose flag and flags refactoring.

- Makefile
Fixes https://github.com/edgexfoundry-holding/edgex-cli/issues/118
> Define GOPATH and GOBIN when undefined within module

- cmd/addressable/list/list.go
- cmd/db/purge/purge.go
- cmd/device/add/add.go
- cmd/device/list/list.go
- cmd/device/rm/rm.go
- cmd/deviceservice/rm/rm.go
- cmd/event/list/list.go
- cmd/event/rm/rm.go
- cmd/interval/rm/rm.go
- cmd/notification/rm/rm.go
- cmd/profile/list/list.go
- cmd/profile/rm/rm.go
- cmd/subscription/list/list.go
- cmd/subscription/rm/rm.go
- config/configuration.go
- go.mod
- pkg/urlclient/factory.go
Started using the go-mod-core-contract clients instead of implementing the rest calls from scratch.
Note:
* Some of the clients are not implemented in go-mod-core-contract. (Addressable list, ds list/rm, ...)
* Not using the registry at this point (future work)
> [wip] Leverage clients provided by go-mod-core-contracts

- cmd/device/add/add.go
'device add' command looks like this:
./edgex-cli device add --file /path/createDevice.toml
Flag --file/-f is required
Changed imports ordering, used: goimports, gofmt
Fixes: https://github.com/edgexfoundry-holding/edgex-cli/issues/143
> Add required `-f` flag in `device add` command

- config/configuration.go
use log.Fatalf instead of log.Fatal
Fixes: https://github.com/edgexfoundry-holding/edgex-cli/issues/158
> Fix error formatting when configuration files fail to parse

- cmd/db/purge/purge.go
Fix: https://github.com/edgexfoundry-holding/edgex-cli/issues/172
> Fix 405 error when delete all logs as part of `db purge` command

- cmd/version/version.go
Fix: https://github.com/edgexfoundry-holding/edgex-cli/issues/180
> Change default Version value from "master" to "dev"

- cmd/interval/add/add.go
- cmd/interval/update/update.go
- cmd/notification/add/add.go
- go.mod
- samples/updateInterval.json
It was not needed to add PUT function in requests.go file, because
of existance of Interval interface.
Start using JSon file as a source :)
Fix: https://github.com/edgexfoundry-holding/edgex-cli/issues/178
> PUT intervals: use go-mod-core-contracts interface client

- cmd/command/list/list.go
- pkg/formatter/formatter.go
FormatWriter interface added
The logic responsible for parsing and executing the template is in
Formatter.Write method
`command list` use it
> Create formatter scaffolding

- pkg/request.go
When --url flag is provided, "httpMethod: url" is printed
Print the correct method
> Print correct http.method

- cmd/device/list/list.go
The message should be about devices, not about device services
Fix: https://github.com/edgexfoundry-holding/edgex-cli/issues/224
> Fix Helper msg in "device list" command

- cmd/reading/count/count.go
- cmd/reading/reading.go
./edgex-cli reading count -> return number of readings in core-data
Partially fix: https://github.com/edgexfoundry-holding/edgex-cli/issues/227
> [feat] add `reading count` command

- pkg/pager/pager.go
Use "more" instead of "less" as default pager
Fixes: https://github.com/edgexfoundry-holding/edgex-cli/issues/127
> [fix]Use "more" as default pager (fix windows problem)

- pkg/cmd/purge/coredata.go
- pkg/cmd/purge/metadata.go
- pkg/cmd/purge/scheduler.go
- api/v1./events/scruball - removes all events and readings
That is why there is not need to execute other request that tries to delete readings
- Cleanup Cleaners interfaces
> [refactor:db purge] Remove unnecessary requests for delete all readings

- cmd/db/purge/purge.go
- cmd/event/count/count.go
- cmd/event/event.go
- cmd/event/rm/rm.go
- cmd/event/scrub/scrub.go
- pkg/confirmation/confirm.go
Add "event scrub" command - that removes all pushed events and associated readings
Add "event scrub --all" command  - scrubs all events and readings from the database
Because both commands could deletes a lot of data -> user is asked for confirmation prior executing the command 
User confirmation logic is refactored
execute gofmt  
Partially fix: https://github.com/edgexfoundry-holding/edgex-cli/issues/226
> [feat][event] New command added: `scrub` --all

- pkg/cmd/purge/coredata.go
- pkg/cmd/purge/interface.go
- pkg/cmd/purge/metadata.go
- pkg/cmd/purge/scheduler.go
Clean up - replace three interfaces with one and the same method with
Purgable interface
Fixes: https://github.com/edgexfoundry-holding/edgex-cli/issues/238
> [db purge]add purgable interface

- cmd/event/scrub/scrub.go
Use more precisе confirmation messages that reminds the client what they are actually doing.
Fixes: https://github.com/edgexfoundry/edgex-cli/issues/258
> event scrub: Use custom confirm msg

- cmd/device/device.go
- cmd/device/list/list.go
- cmd/device/update/update.go
- cmd/deviceservice/deviceservice.go
- cmd/deviceservice/update/update.go
Device update could be updated in two ways ./edgex-cli device update :
- by file that contains one or multiple devices (using -f flag)
- by name. CLI load the device with given name and populates the interactive template,
ready to be modified by the client (--name flag)
Issue:  https://github.com/edgexfoundry/edgex-cli/issues/245
Depends on PR: https://github.com/edgexfoundry/edgex-cli/pull/271
> Support Device Update

- cmd/device/device.go
- cmd/device/update/update.go
- cmd/deviceservice/deviceservice.go
- cmd/interval/add/add.go
Fix: https://github.com/edgexfoundry/edgex-cli/issues/285
> Remove left overs imports that still contains "edgex-holding/cli"

- cmd/device/add/add.go
- cmd/device/update/update.go
- cmd/event/add/add.go
Create device use Json instead of TOLM.
Device create could be updated in two ways ./edgex-cli device create :
- by file that contains one or multiple devices (using -f flag)
- by name - CLI load the device with given name and populates the interactive template,
ready to be modified (using --name flag)
Issue: https://github.com/edgexfoundry/edgex-cli/issues/272
> refactor:create device:Create Device use json type and interactive mode

- cmd/interval/add/add.go
- cmd/notification/add/add.go
Create Notiifications use Json instead of TOML.
Notification could be created by providing file that contains one or
multiple Notifications or by using all other flags including -i (interactive mode)
Issue: https://github.com/edgexfoundry/edgex-cli/issues/274
> refactor:create notification: use Json and interactive mode

- cmd/device/adminstate/adminstatus.go
- cmd/device/adminstate/update/update.go
- cmd/device/device.go
Enable update of device admin state by deviceName or deviceId
Usage Examples:
./edgex-cli device adminstate update  -s LOCKED -d TestRandom-Integer-Device
./edgex-cli device adminstate update  -s unlocked --deviceId 089d3bbf-3795-4ac6-b471-e9645969f720
Closes: https://github.com/edgexfoundry/edgex-cli/issues/247
> feat: update device admin state

- cmd/device/device.go
- cmd/device/operstatus/operstatus.go
(Docs will be update in separate PR)
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.
https://github.com/edgexfoundry/edgex-cli/issues/296
New command for update device operating state is added. Examples: 
./edgex-cli device operstate -n <device_name> -s <OperState>
./edgex-clidevice operstate -i <device_ID> -s <OperState
- [X ] No
No
No
> feat: Add device oper status update command

- cmd/device/rm/rm.go
- cmd/interval/rm/rm.go
- cmd/profile/rm/rm.go
- pkg/request.go
Make Device, Interval and Profile able to delete
multiple objects at once by providing list of Ids
Example:
./edgex-cli device rm [id1] [id2] [id3]
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.
https://github.com/edgexfoundry/edgex-cli/issues/304
> feat: add support of multiple objects delete by id

- .github/PULL_REQUEST_TEMPLATE.md
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.
As you see one line above there is a link for conventional commits . This link cannot be found. This PR change the PR Template to point to correct internal for edgex-cli repository Contributing.md file : https://github.com/edgexfoundry/edgex-cli/blob/master/.github/Contributing.md
https://github.com/edgexfoundry/edgex-cli/issues/314
No
> fix: PR Template point to correct file for conventional commits

- Dockerfile.build
- Makefile
Archie file contains only the executable
https://github.com/edgexfoundry/edgex-cli/issues/324
Add Attribution.txt and LICENSE files in all archive files next to the CLI executable.
- [X ] No
- [ X] No
> feat: Add attribution and Lisence files in archive files

- cmd/command/command.go
- cmd/command/exec/get/get.go
- cmd/command/exec/put/put.go
https://github.com/edgexfoundry/edgex-cli/issues/253 
https://github.com/edgexfoundry/edgex-cli/issues/254
Enable executing get/put commands against core-command microservice
- [X ] No
- [X ] No
Examples: 
./edgex-cli command put -d Random-Float-Device -n Float64 --file ./path/file
./edgex-cli command put -d Random-Float-Device -n Float64 --body '{"filed": "value"}'
./edgex-cli command get -d Random-Float-Device -n Float64
> feat: issue get/put commands

- README.md
- cmd/root.go
- cmd/watcher/add/add.go
- cmd/watcher/list/list.go
- cmd/watcher/rm/rm.go
- cmd/watcher/watcher.go
- [ X] Docs have been added / updated (for bug fixes / features)
https://github.com/edgexfoundry/edgex-cli/issues/330
Add ability to list, add, remove Provisioning watchers
./edgex-cli watcher list 
./edgex-cli watcher rm <id> <id2> ..
./edgex-cli watcher add -f /path-to-file
./edgex-cli watcher add -i -n tests --adminState LOCKED --profileName Hilltop-G-GW --serviceName ev-charger --identifiers 2 --blockingIdentifiers 2
- [X ] No
> feat: Add support of Provisioning watchers

- snap/local/runtime-helpers/bin/edgex-cli-wrapper.sh
- snap/snapcraft.yaml
- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
This PR adds initial snap packaging for edgex-cli. Once published to the store, anyone on a system with snap support will be able to install the client using:
$ sudo snap install edgex-cli
The client can be configured via configuration.toml to run against EdgeX deployed via docker-compose or k8s. The default configuration works with EdgeX deployed natively or via snaps.
> feat: add snap packaging

- snap/local/runtime-helpers/bin/edgex-cli-wrapper.sh
- snap/snapcraft.yaml
Signed-off-by: Tony Espy <espy@canonical.com>
- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
After installing the snap, the first time edgex-cli is run, it will fail due to the client looking for `sample-configuration.toml` via a relative path. I missed this while testing because I built the snap and installed it from the root directory of the git repository, from which the relative path works.
Whenever the client is run via the snap, a wrapper …
> fix(snap): fix initial configuration file install

- Makefile
Do not create /res directory in GOBIN. This is a place for
executables only.
add "@" when echo, thus removing double printing the message
- [x ] No
> fix: `make install` creates $home/.edgex-cli/configuration.toml

- internal/cmd/common.go
- internal/cmd/notification.go
- internal/cmd/subscription.go
- internal/cmd/transmission.go
- internal/service/service.go
This commit adds support for support-notification enpoints:
- notification [add/cleanup/list/rm]
- subscription [add/get/list/rm]
- transmission [get/list/rm]
Fix #392
Fix #389
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>
1. Install EdgeXFoundry and start up support-notifications service
2. Build the CLI from this PR with `make build` and test the commands as follows:
```
./bin/edgex-cli notification
./bin/edgex-cli notification add -h
./bin/edgex-cli notification add -s "sender01" -c "content" --category …
```
> feat: add V2 support-notifications

- internal/cmd/common.go
- internal/cmd/interval.go
- internal/cmd/intervalaction.go
- internal/service/service.go
This commit adds support for support-scheduler endpoints:
- interval [add,name,list,rm,update]
- intervalaction [add,name,list,rm,update]
Fix #388
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>
1. Install EdgeXFoundry and start up support-scheduler service
2. Build the CLI from this PR with `make build` and test the commands as follows:
```
./bin/edgex-cli interval
./bin/edgex-cli interval add -h
./bin/edgex-cli interval add -n "hourly" -i "1h"
./bin/edgex-cli interval name -h
./bin/edgex-cli interval name -n …
```
> feat: add V2 support-scheduler

- .gitignore
- snap/snapcraft.yaml
The metadata kept in snapcraft.yaml is obsolete because it is being overridden on the store. This change will allow sourcing the central copy of metadata.
See https://github.com/canonical/edgex-snap-metadata/issues/2
Signed-off-by: Mengyi Wang <mengyi.wang@canonical.com>
```
$ snapcraft clean && snapcraft
$ unsquashfs name.snap
$ ls squashfs-root/meta/gui/icon.png 
squashfs-root/meta/gui/icon.png
$ cat squashfs-root/meta/snap.yaml
name: edgex-cli
version: 2.0.0-dev.20
summary: EdgeX CLI
description: |-
EdgeX CLI is a …
```
> build(snap): source metadata from central repo

- Dockerfile.build
- Makefile
- bin/test-attribution-txt.sh
- go.mod
- snap/snapcraft.yaml
Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>
run `make test build`
> build: Upgrade to Go 1.18 and optimize attribution script
