- cmd/devices.go
> Removes extra text

- cmd/device/device.go
- cmd/device/list/list.go
- cmd/device/rm/rm.go
- cmd/event/event.go
- cmd/event/rm/rm.go
- cmd/profile/list/list.go
- cmd/profile/profile.go
- cmd/profile/rm/rm.go
- main.go
> Adds copyright information to each file

- cmd/deviceservice/deviceservice.go
- cmd/deviceservice/list/list.go
- cmd/deviceservice/rm/rm.go
- cmd/root.go
> Adds device service commands

- cmd/profile/add/add.go
- cmd/profile/profile.go
Signed-off-by: Iain Anderson <iain@iotechsys.com>
> Add profile upload command

- README.md
> Adds small README file

- cmd/deviceservice/deviceservice.go
- cmd/profile/profile.go
- cmd/root.go
> Adds more help messages and a welcome banner.

- README.md
- go.mod
> Adds go.mod file and updates README

- cmd/device/list/list.go
- cmd/deviceservice/list/list.go
- cmd/profile/list/list.go
> Fixes bug in time formatting

- cmd/device/list/list.go
- cmd/deviceservice/list/list.go
- cmd/profile/list/list.go
- pkg/utils/utils.go
> Creates pkg/ subdirectory and implements utils package

- .gitignore
- Makefile
- cmd/root.go
- go.mod
> Adds makefile with ability to install binary system-wide

- README.md
> Adds issue link in readme but reference to bug

- .github/1-bug-report.md
- .github/2-feature-request.md
- .github/3-docs-bug.md
- .github/4-security-issue-disclosure.md
- .github/5-support-request.md
> Adds issue templates

- .github/ISSUE_TEMPLATE/1-bug-report.md
- .github/ISSUE_TEMPLATE/2-feature-request.md
> Updates Github issue templates

- cmd/profile/list/list.go
- cmd/root.go
- cmd/status/status.go
> Adds status command

- README.md
- go.mod
> Apply interim Go modules bug fix.

- README.md
> Put a Go Report Badge

- cmd/event/event.go
- cmd/event/list/list.go
> Add Event List command

- cmd/device/list/list.go
- cmd/deviceservice/list/list.go
- cmd/event/list/list.go
- cmd/profile/list/list.go
> Fixes typos

- cmd/profile/add/add.go
- pkg/utils/utils.go
Adds comments on exported functions and formats profile/add with gofmt
> Addresses issues in go report card.

- README.md
- cmd/reading/list/list.go
- cmd/reading/reading.go
- cmd/root.go
> Add Readings List command with device and limit flags

- cmd/event/list/list.go
> Add event by device command

- cmd/purgedb/purgedb.go
> Changed command description for purgeDB.

- README.md
- cmd/event/list/list.go
- cmd/notification/add/add.go
- cmd/notification/notification.go
- cmd/notification/rm/rm.go
- cmd/root.go
- cmd/subscription/add/add.go
- cmd/subscription/rm/rm.go
- cmd/subscription/subscription.go
> Add notifications and subscriptions commmands

- cmd/root.go
- cmd/status/status.go
- pkg/client.go
> Configurable host location

- cmd/status/status.go
> Removes [BETA] tag from status command

- cmd/db/db.go
- cmd/db/purge/purge.go
- cmd/root.go
> Changes purgedb to db purge

- cmd/db/purge/purge.go
- cmd/device/rm/rm.go
- pkg/client.go
> Purge DB removes data from all other services

- cmd/db/purge/purge.go
- cmd/root.go
- pkg/client.go
> Adds verbose flags that applies to commands using pkg/client.go

- pkg/client.go
> Fixes issue with URL formatting

- cmd/db/purge/purge.go
- cmd/root.go
- pkg/client.go
> Fixes verbose flag and add return value to delete functions in client

- cmd/device/list/list.go
- cmd/device/rm/rm.go
- cmd/deviceservice/list/list.go
- cmd/deviceservice/rm/rm.go
> Device and device service rm/list command now use client.go

- cmd/profile/list/list.go
- cmd/profile/rm/rm.go
> Profile list/rm use pkg/client.go

- README.md
> Changes Available commands section format

- cmd/db/purge/purge.go
- cmd/device/rm/rm.go
- cmd/deviceservice/rm/rm.go
- cmd/profile/rm/rm.go
- pkg/client.go
> Adds ability to remove from either name or ID to client.go

- cmd/root.go
- config/configuration.go
- pkg/client.go
> [WIP] Add configuration file and structs - do not merge

- README.md
- cmd/interval/add/add.go
- cmd/interval/interval.go
- cmd/interval/list/list.go
- cmd/interval/rm/rm.go
- cmd/interval/update/update.go
- cmd/root.go
- pkg/client.go
> Add interval command

- cmd/version/version.go
- pkg/client.go
Was not able to test as current branch of edgex-go does not build
> [WIP] Add GetVersion function to get version of each microservice

- Makefile
- cmd/version/version.go
- go.mod
> Changes last instances of edgexfoundry/edgex-cli

- Makefile
- cmd/root.go
- go.mod
> Changes GOMOD to ON in makefile and Module name in go.mod

- cmd/db/purge/purge.go
- cmd/device/list/list.go
- cmd/device/rm/rm.go
- cmd/deviceservice/list/list.go
- cmd/deviceservice/rm/rm.go
- cmd/interval/rm/rm.go
- cmd/profile/list/list.go
- cmd/profile/rm/rm.go
- pkg/client.go
- pkg/client_test.go
- pkg/const.go
> Add unit tests for pkg/client.go

- cmd/root.go
- config/configuration.go
> Creates config directory on startup if doesn't exists

- cmd/device/list/list.go
> Removes Created time from Device command

- cmd/profile/rm/rm.go
> Fix Device Profile Remove

- Makefile
- README.md
- go.mod
Signed-off-by: Alexandre Courouble <acourouble@acourouble-a01.vmware.com>
> Updates the README and the Makefile

- Makefile
- README.md
- config/configuration.go
- config/configuration_test.go
> Add test entry to Makefile

- README.md
> Removes examples from readme

- config/configuration.go
- go.mod
> Fixes missing host in config

- cmd/subscription/list/list.go
- cmd/subscription/subscription.go
> Add subscription list command

- cmd/addressable/addressable.go
- cmd/addressable/list/list.go
- cmd/root.go
- config/configuration.go
> Adds addressable command and list subcommand

- cmd/device/add/add.go
- cmd/event/list/list.go
- cmd/interval/add/add.go
- cmd/interval/list/list.go
- cmd/interval/update/update.go
- cmd/notification/add/add.go
- cmd/profile/add/add.go
- cmd/reading/list/list.go
- cmd/subscription/add/add.go
Some commands directed to a different host did not work due to hard-coded URLs started with http://localhost/.
Make it work correctly by building URLs with a value from config.yaml.
> Changed hard-coded URLs for localhost to use value from config.yaml.

- config/configuration.go
- go.mod
> Fixes dependencies issues

- Makefile
Fixes https://github.com/edgexfoundry-holding/edgex-cli/issues/138
> fixes ifndef test in Makefile

- Makefile
Fixes https://github.com/edgexfoundry-holding/edgex-cli/issues/132
> Fixes GOBIN defined test

- cmd/db/purge/purge.go
- config/configuration_test.go
- config/testdata/config.yaml
> removes references to deprecated export service

- Makefile
> install copies over template configuration.toml file to $HOME/.edgex-cli/

- cmd/event/list/list.go
- cmd/interval/list/list.go
- cmd/reading/list/list.go
- pkg/utils/utils.go
#163 -- partial solution listHelper in utils.go
> tackles list error when excessive data retrieval attempted

- config/configuration.go
- config/configuration_test.go
a little more clean up for #142
> loadconfig on error returns consistent error object

- cmd/addressable/list/list.go
- cmd/db/purge/purge.go
- cmd/device/list/list.go
- cmd/deviceservice/list/list.go
- cmd/event/list/list.go
- cmd/interval/list/list.go
- cmd/notification/rm/rm.go
- cmd/profile/list/list.go
- cmd/reading/list/list.go
- cmd/subscription/list/list.go
- pkg/client.go
- pkg/cmd/purge/coredata.go
- pkg/cmd/purge/metadata.go
- pkg/cmd/purge/scheduler.go
- pkg/utils/utils.go
Start usung ListHelper function instead of GetAllItems
Depricte GetAllItems function
All commands with list action use RunE instead of Run
Created cleaner interface per microservice
Partially fixes https://github.com/edgexfoundry-holding/edgex-cli/issues/153
> Addressing comments in PR #165

- cmd/event/list/list.go
- cmd/interval/list/list.go
- cmd/reading/list/list.go
- go.mod
- pkg/utils/utils.go
> fixes merge issues stemming from introducing DIsplayDuration

- cmd/interval/list/list.go
- cmd/notification/rm/rm.go
- config/configuration_test.go
- pkg/client.go
- pkg/cmd/purge/metadata.go
- pkg/cmd/purge/scheduler.go
Fix issues listed int the issue #170 
Fix:https://github.com/edgexfoundry-holding/edgex-cli/issues/170
> Address "golangCI run" reported issues

- samples/createDP.yaml
- samples/createDevice.toml
- samples/createInterval.toml
- samples/createNotifications.toml
Fix: https://github.com/edgexfoundry-holding/edgex-cli/issues/184
> Add Sample file for Create: device, profile,notification, interval

- cmd/db/purge/purge.go
- cmd/interval/add/add.go
- cmd/notification/add/add.go
- cmd/notification/rm/rm.go
- cmd/profile/add/add.go
- cmd/reading/list/list.go
- cmd/root.go
- cmd/subscription/add/add.go
- cmd/subscription/subscription.go
- go.mod
- pkg/cmd/purge/coredata.go
- pkg/cmd/purge/metadata.go
- pkg/cmd/purge/scheduler.go
- pkg/request.go
- pkg/utils/utils.go
Add support for --verbose and --url flags in request.go file
depricate subscription
add SilenceUsage
Fix: https://github.com/edgexfoundry-holding/edgex-cli/issues/177
> Use go-mod-core-contracts for creating requests

- cmd/notification/list/list.go
- cmd/notification/notification.go
start and end variants not tested
verbose and url flags not treated .
partially addresses #129
> Supports Notification list #129

- cmd/root.go
Move the logic closing the Writer from PersistentPostRun to a new deferred function
os.Exit(1) is also deferred, so if cmd.Execute returns an error first the Writer to be close and the os.Exit(1) to be called
Fix: https://github.com/edgexfoundry-holding/edgex-cli/issues/186
> Create defer func that close the Writer

- README.md
- cmd/event/add/add.go
- cmd/event/event.go
- cmd/root.go
- go.mod
- pkg/editor/interactive.go
Fix #100
Create new Add sub-command for Event.
Add functionality for Interactive mode which allows users to provide
information via the editor of their choice.
Updated README to include new Interactive mode functionality.
Signed-off-by: Anthony M. Bonafide <AnthonyMBonafide@gmail.com>
> Create Add Sub-command for Event

- cmd/deviceservice/rm/rm.go
- cmd/subscription/list/list.go
- cmd/subscription/rm/rm.go
- pkg/request.go
Partially Fix : https://github.com/edgexfoundry-holding/edgex-cli/issues/157
> Remove DeleteItemByIdOrName method

- cmd/notification/list/list.go
> checks verbose and url flags. shortens help string

- Makefile
Address Uninstall entry in makefile 
Fix #59
> support uninstall

- run_cmds.sh
> Add bash file that could help when testing locally

- cmd/interval/list/list.go
Use go-mod-core-contracts to retrieve all intervals or a single interval by ID
and by doing this fix exception: cannot unmarshal object into Go value of type []models.Interval
Fix: https://github.com/edgexfoundry-holding/edgex-cli/issues/203
> Fix listing interval by Id command

- cmd/command/command.go
- cmd/command/list/list.go
- cmd/root.go
- go.mod
- res/configuration.toml
add `command list --device <devicename>
--device is mandaroty field
> add `command list --device <devicename>

- cmd/addressable/list/list.go
Print addressable HTTPMethod, Address and Port as well
> Use formatter interface for addressable list

- cmd/notification/rm/rm.go
- delete by age and slug happens by using flags
- change Usage msg, and flags description
> Notification remove use flags

- cmd/deviceservice/list/list.go
Add support of Get deviceService by name/id
Current supported commands under "deviceservice list" are:
./edgex-cli deviceservice list - returns the list of device services
./edgex-cli deviceservice list <id> - returns device service matching the given id
./edgex-cli device service list --name <ds_name> - returns device service matching the given name
Fixes https://github.com/edgexfoundry/edgex-cli/issues/252 , https://github.com/edgexfoundry/edgex-cli/issues/251
> Support Get DeviceService by name/id

- cmd/deviceservice/add/add.go
- cmd/deviceservice/deviceservice.go
The command support adding DS from:
- file ( providing -f flag)
- interactive mode (-i flag + all other available flags)
> new command: add deviceservice

- cmd/device/list/list.go
Support Get Device by Name
Current supported command under "device list" are:
`./edgex-cli device list` - returns the list of devices
`./edgex-cli device list --name <device_name>` - return device matching the given name, if any
Fixes https://github.com/edgexfoundry/edgex-cli/issues/246
> Support Get Device by Name

- Attribution.txt
- cmd/profile/add/add.go
- go.mod
- samples/createDP.json
refactored create of Device Profile to use Json format
Enable interactive mode and file
Closes:https://github.com/edgexfoundry/edgex-cli/issues/301
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.
> refactor: create device profile to use Json

- cmd/profile/add/add.go
- cmd/profile/profile.go
- cmd/profile/update/update.go
- go.mod
- pkg/editor/interactive.go
This command is missing
https://github.com/edgexfoundry/edgex-cli/issues/248
https://github.com/edgexfoundry/edgex-cli/issues/317
Support update of Device Profile. Two file formats are supported json and yaml
- [ X] No
gopkg.in/yaml.v2 v2.2.8
> feat: add command for update Device Profile

- .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: Jim White <jpwhite_mn@yahoo.com>
add y/n checkboxes to PR template for new imports
> fix: added y/n checkboxes for new imports

- README.md
- cmd/profile/update/update.go
- cmd/status/status.go
- [X ] Docs have been added / updated (for bug fixes / features)
https://github.com/edgexfoundry/edgex-cli/issues/328
This PR updates:
- README file to contain all supported commands.
- Helper message of `status` command
- fix some of the messaged in profile update command
- [ X] No
- [X ] No
> fix: Update edgex-cli documentation

- cmd/profile/profile.go
Inaccurate DP helper message 
https://github.com/edgexfoundry/edgex-cli/issues/337
- [ X] No
- [X ] No
> fix: Make Device Profile message more accurate

- Dockerfile.build
Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>
> ci: standardize dockerfiles

- .gitignore
- Dockerfile.build
- go.mod
update go.mod and Dockerfile.build
Signed-off-by: Jim White <jpwhite_mn@yahoo.com>
n/a
n/a
upgrade Go from 1.15 to 1.16
> build: upgrade Go Lang to 1.16

- snap/README.md
This PR adds a missing README.md file for snap deployment
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>
N/A
> docs(snap): add snap README.md

- Dockerfile.build
Changes related to Go 1.17 and cache optimizations
> ci: Go 1.17 related changes

- bin/test-attribution-txt.sh
- go.mod
- snap/snapcraft.yaml
Changes related to Go 1.17 module changes
> ci: gomod changes related for Go 1.17

- CHANGELOG.md
includes changelog for Jakarta as there was no initial file
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>
> docs: added Changelog for Kamakura
